version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  # We have REMOVED the ApplicationStop hook to bypass the error.
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
