version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user

  # --- FIX: ADD THIS NEW HOOK ---
  # This hook runs after the 'files' section is completed.
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root # We use root to ensure we have permission to run chmod
  # --- End of FIX ---

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
